version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - go-microservice-postgres:/data/postgres
      - ./databases/postgres/create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
      - ./databases/postgres/backup:/backup  # Mapping backup directory
    restart: always
    networks:
      - postgres-network

  redis:
    image: redis
    container_name: redis
    ports: 
      - 6379:6379
    volumes: 
      - go-microservice-redis:/data
      - ./databases/redis:/data
      - ./config/redis.conf:/redis.conf
    command: redis-server /redis.conf


  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   env_file:
  #     - .env
  #   ports:
  #     - "16543:80"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - postgres-network


volumes:
  go-microservice-postgres:
  go-microservice-redis:
networks: 
  postgres-network:
    driver: bridge